export type Lane = '对抗路' | '打野' | '中路' | '发育路' | '游走'

export interface Hero {
  id: string
  name: string
  lanes: Lane[]
}

export const lanes: Lane[] = ['对抗路', '打野', '中路', '发育路', '游走']

/** 数据来源：王者荣耀官网英雄列表（pvp.qq.com/web201605/js/herolist.json），随版本人工更新 */
export const heroes: Hero[] = [
  { id: 'lianpo', name: '廉颇', lanes: ['对抗路', '游走'] },
  { id: 'xiaoqiao', name: '小乔', lanes: ['中路'] },
  { id: 'zhaoyun', name: '赵云', lanes: ['打野'] },
  { id: 'mozi', name: '墨子', lanes: ['中路', '游走'] },
  { id: 'daji', name: '妲己', lanes: ['中路'] },
  { id: 'yingzheng', name: '嬴政', lanes: ['中路'] },
  { id: 'sunshangxiang', name: '孙尚香', lanes: ['发育路'] },
  { id: 'lubanqihao', name: '鲁班七号', lanes: ['发育路'] },
  { id: 'zhuangzhou', name: '庄周', lanes: ['游走'] },
  { id: 'liushan', name: '刘禅', lanes: ['游走'] },
  { id: 'gaojianli', name: '高渐离', lanes: ['中路'] },
  { id: 'ake', name: '阿轲', lanes: ['打野'] },
  { id: 'zhongwuyan', name: '钟无艳', lanes: ['对抗路', '打野'] },
  { id: 'sunbin', name: '孙膑', lanes: ['游走'] },
  { id: 'bianque', name: '扁鹊', lanes: ['中路'] },
  { id: 'sunwukong', name: '孙悟空', lanes: ['打野'] },
  { id: 'xinmoliuer', name: '心魔六耳', lanes: ['打野', '对抗路'] },
  { id: 'baiqi', name: '白起', lanes: ['对抗路'] },
  { id: 'miyue', name: '芈月', lanes: ['对抗路', '打野'] },
  { id: 'lvbu', name: '吕布', lanes: ['对抗路'] },
  { id: 'zhouyv', name: '周瑜', lanes: ['中路'] },
  { id: 'xiahoudun', name: '夏侯惇', lanes: ['对抗路', '游走', '打野'] },
  { id: 'zhenji', name: '甄姬', lanes: ['中路'] },
  { id: 'caocao', name: '曹操', lanes: ['对抗路', '打野'] },
  { id: 'dianwei', name: '典韦', lanes: ['打野'] },
  { id: 'gongbenwuzang', name: '宫本武藏', lanes: ['打野'] },
  { id: 'libai', name: '李白', lanes: ['打野'] },
  { id: 'makeboluo', name: '马可波罗', lanes: ['发育路'] },
  { id: 'direnjie', name: '狄仁杰', lanes: ['发育路'] },
  { id: 'damo', name: '达摩', lanes: ['对抗路'] },
  { id: 'xiangyu', name: '项羽', lanes: ['对抗路', '游走'] },
  { id: 'wuzetian', name: '武则天', lanes: ['中路'] },
  { id: 'laofuzi', name: '老夫子', lanes: ['对抗路'] },
  { id: 'guanyu', name: '关羽', lanes: ['对抗路'] },
  { id: 'diaochan', name: '貂蝉', lanes: ['中路', '对抗路'] },
  { id: 'anqila', name: '安琪拉', lanes: ['中路'] },
  { id: 'chengyaojin', name: '程咬金', lanes: ['对抗路'] },
  { id: 'luna', name: '露娜', lanes: ['打野'] },
  { id: 'jiangziya', name: '姜子牙', lanes: ['中路', '游走'] },
  { id: 'liubang', name: '刘邦', lanes: ['对抗路', '游走'] },
  { id: 'hanxin', name: '韩信', lanes: ['打野'] },
  { id: 'wangzhaojun', name: '王昭君', lanes: ['中路', '游走'] },
  { id: 'lanlingwang', name: '兰陵王', lanes: ['打野'] },
  { id: 'huamulan', name: '花木兰', lanes: ['对抗路'] },
  { id: 'zhangliang', name: '张良', lanes: ['中路', '游走'] },
  { id: 'buzhihuowu', name: '不知火舞', lanes: ['中路'] },
  { id: 'nakelulu', name: '娜可露露', lanes: ['打野'] },
  { id: 'jvyoujing', name: '橘右京', lanes: ['打野', '对抗路'] },
  { id: 'yase', name: '亚瑟', lanes: ['对抗路', '打野'] },
  { id: 'niumo', name: '牛魔', lanes: ['游走'] },
  { id: 'houyi', name: '后羿', lanes: ['发育路'] },
  { id: 'liubei', name: '刘备', lanes: ['打野'] },
  { id: 'zhangfei', name: '张飞', lanes: ['游走'] },
  { id: 'liyuanfang', name: '李元芳', lanes: ['发育路', '打野'] },
  { id: 'yuji', name: '虞姬', lanes: ['发育路'] },
  { id: 'zhongkui', name: '钟馗', lanes: ['游走'] },
  { id: 'yangjian', name: '杨戬', lanes: ['对抗路', '打野'] },
  { id: 'yadianna', name: '雅典娜', lanes: ['打野'] },
  { id: 'caiwenji', name: '蔡文姬', lanes: ['游走'] },
  { id: 'taiyizhenren', name: '太乙真人', lanes: ['游走'] },
  { id: 'nezha', name: '哪吒', lanes: ['对抗路', '打野'] },
  { id: 'zhugeliang', name: '诸葛亮', lanes: ['中路', '打野'] },
  { id: 'huangzhong', name: '黄忠', lanes: ['发育路'] },
  { id: 'daqiao', name: '大乔', lanes: ['游走', '中路'] },
  { id: 'donghuangtaiyi', name: '东皇太一', lanes: ['游走', '对抗路'] },
  { id: 'ganjiangmoye', name: '干将莫邪', lanes: ['中路'] },
  { id: 'guiguzi', name: '鬼谷子', lanes: ['游走'] },
  { id: 'kai', name: '铠', lanes: ['打野', '对抗路'] },
  { id: 'bailishouyue', name: '百里守约', lanes: ['发育路'] },
  { id: 'bailixuance', name: '百里玄策', lanes: ['打野'] },
  { id: 'sulie', name: '苏烈', lanes: ['游走', '对抗路'] },
  { id: 'mengqi', name: '梦奇', lanes: ['对抗路', '打野'] },
  { id: 'nvwa', name: '女娲', lanes: ['中路'] },
  { id: 'mingshiyin', name: '明世隐', lanes: ['游走'] },
  { id: 'gongsunli', name: '公孙离', lanes: ['发育路'] },
  { id: 'yangyuhuan', name: '杨玉环', lanes: ['中路', '游走', '打野'] },
  { id: 'peiqinhu', name: '裴擒虎', lanes: ['打野'] },
  { id: 'yixing', name: '弈星', lanes: ['中路'] },
  { id: 'kuangtie', name: '狂铁', lanes: ['对抗路'] },
  { id: 'milaidi', name: '米莱狄', lanes: ['中路'] },
  { id: 'yuange', name: '元歌', lanes: ['对抗路'] },
  { id: 'sunce', name: '孙策', lanes: ['对抗路', '打野'] },
  { id: 'simayi', name: '司马懿', lanes: ['打野', '中路'] },
  { id: 'dunshan', name: '盾山', lanes: ['游走'] },
  { id: 'jialuo', name: '伽罗', lanes: ['发育路'] },
  { id: 'shenmengxi', name: '沈梦溪', lanes: ['中路'] },
  { id: 'lixin', name: '李信', lanes: ['对抗路'] },
  { id: 'shangguanwaner', name: '上官婉儿', lanes: ['中路'] },
  { id: 'change', name: '嫦娥', lanes: ['中路', '对抗路', '打野'] },
  { id: 'zhubajie', name: '猪八戒', lanes: ['对抗路', '打野'] },
  { id: 'pangu', name: '盘古', lanes: ['打野', '对抗路'] },
  { id: 'yao', name: '瑶', lanes: ['游走'] },
  { id: 'yunzhongjun', name: '云中君', lanes: ['打野'] },
  { id: 'dongfangyao', name: '曜', lanes: ['打野', '对抗路'] },
  { id: 'machao', name: '马超', lanes: ['对抗路', '打野'] },
  { id: 'xishi', name: '西施', lanes: ['中路'] },
  { id: 'lubandashi', name: '鲁班大师', lanes: ['游走'] },
  { id: 'mengya', name: '蒙犽', lanes: ['发育路'] },
  { id: 'jing', name: '镜', lanes: ['打野'] },
  { id: 'mengtian', name: '蒙恬', lanes: ['对抗路'] },
  { id: 'aguduo', name: '阿古朵', lanes: ['打野', '发育路'] },
  { id: 'xialuote', name: '夏洛特', lanes: ['对抗路'] },
  { id: 'lan', name: '澜', lanes: ['打野'] },
  { id: 'sikongzhen', name: '司空震', lanes: ['对抗路', '打野'] },
  { id: 'ailin', name: '艾琳', lanes: ['发育路'] },
  { id: 'yunying', name: '云缨', lanes: ['打野'] },
  { id: 'jinchan', name: '金蝉', lanes: ['中路', '游走'] },
  { id: 'fei', name: '暃', lanes: ['打野'] },
  { id: 'sangqi', name: '桑启', lanes: ['游走'] },
  { id: 'geya', name: '戈娅', lanes: ['发育路'] },
  { id: 'haiyue', name: '海月', lanes: ['中路'] },
  { id: 'zhaohuaizhen', name: '赵怀真', lanes: ['打野', '对抗路', '游走'] },
  { id: 'laixiao', name: '莱西奥', lanes: ['发育路'] },
  { id: 'jixiaoman', name: '姬小满', lanes: ['对抗路'] },
  { id: 'yalian', name: '亚连', lanes: ['对抗路'] },
  { id: 'duoliya', name: '朵莉亚', lanes: ['游走'] },
  { id: 'hainuo', name: '海诺', lanes: ['中路', '对抗路'] },
  { id: 'aoyin', name: '敖隐', lanes: ['发育路'] },
  { id: 'dasiming', name: '大司命', lanes: ['打野', '对抗路'] },
  { id: 'yuanliuzhizi_magic', name: '元流之子(法师)', lanes: ['中路'] },
  { id: 'yuanliuzhizi_tank', name: '元流之子(坦克)', lanes: ['对抗路', '打野'] },
  { id: 'shaosiyuan', name: '少司缘', lanes: ['游走'] },
  { id: 'ying', name: '影', lanes: ['对抗路', '打野'] },
  { id: 'cang', name: '苍', lanes: ['发育路', '打野'] },
  { id: 'kongkonger', name: '空空儿', lanes: ['游走'] },
  { id: 'yuanliuzhizi_archer', name: '元流之子(射手)', lanes: ['发育路'] },
  { id: 'sunquan', name: '孙权', lanes: ['发育路'] },
  { id: 'chicha', name: '蚩奼', lanes: ['对抗路', '打野'] },
  { id: 'yuanliuzhizi_support', name: '元流之子(辅助)', lanes: ['游走'] },
  { id: 'dayu', name: '大禹', lanes: ['游走'] },
  { id: 'yuanliuzhizi_assassin', name: '元流之子(刺客)', lanes: ['打野'] },
  { id: 'luyana', name: '卢雅那', lanes: ['游走'] },
  { id: 'wangwei', name: '王维', lanes: ['打野'] },
]
