export type Lane = '对抗路' | '打野' | '中路' | '发育路' | '游走'

export interface Hero {
  id: string
  /** 官方英雄数字 id（ename），用于拼官方形象图片路径 */
  officialId: number
  name: string
  lanes: Lane[]
}

export const lanes: Lane[] = ['对抗路', '打野', '中路', '发育路', '游走']

/** 数据来源：王者荣耀官网英雄列表（pvp.qq.com/web201605/js/herolist.json），随版本人工更新 */
export const heroes: Hero[] = [
  { id: 'lianpo', officialId: 105, name: '廉颇', lanes: ['对抗路', '游走'] },
  { id: 'xiaoqiao', officialId: 106, name: '小乔', lanes: ['中路'] },
  { id: 'zhaoyun', officialId: 107, name: '赵云', lanes: ['打野'] },
  { id: 'mozi', officialId: 108, name: '墨子', lanes: ['中路', '游走'] },
  { id: 'daji', officialId: 109, name: '妲己', lanes: ['中路'] },
  { id: 'yingzheng', officialId: 110, name: '嬴政', lanes: ['中路'] },
  { id: 'sunshangxiang', officialId: 111, name: '孙尚香', lanes: ['发育路'] },
  { id: 'lubanqihao', officialId: 112, name: '鲁班七号', lanes: ['发育路'] },
  { id: 'zhuangzhou', officialId: 113, name: '庄周', lanes: ['游走'] },
  { id: 'liushan', officialId: 114, name: '刘禅', lanes: ['游走'] },
  { id: 'gaojianli', officialId: 115, name: '高渐离', lanes: ['中路'] },
  { id: 'ake', officialId: 116, name: '阿轲', lanes: ['打野'] },
  { id: 'zhongwuyan', officialId: 117, name: '钟无艳', lanes: ['对抗路', '打野'] },
  { id: 'sunbin', officialId: 118, name: '孙膑', lanes: ['游走'] },
  { id: 'bianque', officialId: 119, name: '扁鹊', lanes: ['中路'] },
  { id: 'sunwukong', officialId: 167, name: '孙悟空', lanes: ['打野'] },
  { id: 'xinmoliuer', officialId: 549, name: '心魔六耳', lanes: ['打野', '对抗路'] },
  { id: 'baiqi', officialId: 120, name: '白起', lanes: ['对抗路'] },
  { id: 'miyue', officialId: 121, name: '芈月', lanes: ['对抗路', '打野'] },
  { id: 'lvbu', officialId: 123, name: '吕布', lanes: ['对抗路'] },
  { id: 'zhouyv', officialId: 124, name: '周瑜', lanes: ['中路'] },
  { id: 'xiahoudun', officialId: 126, name: '夏侯惇', lanes: ['对抗路', '游走', '打野'] },
  { id: 'zhenji', officialId: 127, name: '甄姬', lanes: ['中路'] },
  { id: 'caocao', officialId: 128, name: '曹操', lanes: ['对抗路', '打野'] },
  { id: 'dianwei', officialId: 129, name: '典韦', lanes: ['打野'] },
  { id: 'gongbenwuzang', officialId: 130, name: '宫本武藏', lanes: ['打野'] },
  { id: 'libai', officialId: 131, name: '李白', lanes: ['打野'] },
  { id: 'makeboluo', officialId: 132, name: '马可波罗', lanes: ['发育路'] },
  { id: 'direnjie', officialId: 133, name: '狄仁杰', lanes: ['发育路'] },
  { id: 'damo', officialId: 134, name: '达摩', lanes: ['对抗路'] },
  { id: 'xiangyu', officialId: 135, name: '项羽', lanes: ['对抗路', '游走'] },
  { id: 'wuzetian', officialId: 136, name: '武则天', lanes: ['中路'] },
  { id: 'laofuzi', officialId: 139, name: '老夫子', lanes: ['对抗路'] },
  { id: 'guanyu', officialId: 140, name: '关羽', lanes: ['对抗路'] },
  { id: 'diaochan', officialId: 141, name: '貂蝉', lanes: ['中路', '对抗路'] },
  { id: 'anqila', officialId: 142, name: '安琪拉', lanes: ['中路'] },
  { id: 'chengyaojin', officialId: 144, name: '程咬金', lanes: ['对抗路'] },
  { id: 'luna', officialId: 146, name: '露娜', lanes: ['打野'] },
  { id: 'jiangziya', officialId: 148, name: '姜子牙', lanes: ['中路', '游走'] },
  { id: 'liubang', officialId: 149, name: '刘邦', lanes: ['对抗路', '游走'] },
  { id: 'hanxin', officialId: 150, name: '韩信', lanes: ['打野'] },
  { id: 'wangzhaojun', officialId: 152, name: '王昭君', lanes: ['中路', '游走'] },
  { id: 'lanlingwang', officialId: 153, name: '兰陵王', lanes: ['打野'] },
  { id: 'huamulan', officialId: 154, name: '花木兰', lanes: ['对抗路'] },
  { id: 'zhangliang', officialId: 156, name: '张良', lanes: ['中路', '游走'] },
  { id: 'buzhihuowu', officialId: 157, name: '不知火舞', lanes: ['中路'] },
  { id: 'nakelulu', officialId: 162, name: '娜可露露', lanes: ['打野'] },
  { id: 'jvyoujing', officialId: 163, name: '橘右京', lanes: ['打野', '对抗路'] },
  { id: 'yase', officialId: 166, name: '亚瑟', lanes: ['对抗路', '打野'] },
  { id: 'niumo', officialId: 168, name: '牛魔', lanes: ['游走'] },
  { id: 'houyi', officialId: 169, name: '后羿', lanes: ['发育路'] },
  { id: 'liubei', officialId: 170, name: '刘备', lanes: ['打野'] },
  { id: 'zhangfei', officialId: 171, name: '张飞', lanes: ['游走'] },
  { id: 'liyuanfang', officialId: 173, name: '李元芳', lanes: ['发育路', '打野'] },
  { id: 'yuji', officialId: 174, name: '虞姬', lanes: ['发育路'] },
  { id: 'zhongkui', officialId: 175, name: '钟馗', lanes: ['游走'] },
  { id: 'yangjian', officialId: 178, name: '杨戬', lanes: ['对抗路', '打野'] },
  { id: 'yadianna', officialId: 183, name: '雅典娜', lanes: ['打野'] },
  { id: 'caiwenji', officialId: 184, name: '蔡文姬', lanes: ['游走'] },
  { id: 'taiyizhenren', officialId: 186, name: '太乙真人', lanes: ['游走'] },
  { id: 'nezha', officialId: 180, name: '哪吒', lanes: ['对抗路', '打野'] },
  { id: 'zhugeliang', officialId: 190, name: '诸葛亮', lanes: ['中路', '打野'] },
  { id: 'huangzhong', officialId: 192, name: '黄忠', lanes: ['发育路'] },
  { id: 'daqiao', officialId: 191, name: '大乔', lanes: ['游走', '中路'] },
  { id: 'donghuangtaiyi', officialId: 187, name: '东皇太一', lanes: ['游走', '对抗路'] },
  { id: 'ganjiangmoye', officialId: 182, name: '干将莫邪', lanes: ['中路'] },
  { id: 'guiguzi', officialId: 189, name: '鬼谷子', lanes: ['游走'] },
  { id: 'kai', officialId: 193, name: '铠', lanes: ['打野', '对抗路'] },
  { id: 'bailishouyue', officialId: 196, name: '百里守约', lanes: ['发育路'] },
  { id: 'bailixuance', officialId: 195, name: '百里玄策', lanes: ['打野'] },
  { id: 'sulie', officialId: 194, name: '苏烈', lanes: ['游走', '对抗路'] },
  { id: 'mengqi', officialId: 198, name: '梦奇', lanes: ['对抗路', '打野'] },
  { id: 'nvwa', officialId: 179, name: '女娲', lanes: ['中路'] },
  { id: 'mingshiyin', officialId: 501, name: '明世隐', lanes: ['游走'] },
  { id: 'gongsunli', officialId: 199, name: '公孙离', lanes: ['发育路'] },
  { id: 'yangyuhuan', officialId: 176, name: '杨玉环', lanes: ['中路', '游走', '打野'] },
  { id: 'peiqinhu', officialId: 502, name: '裴擒虎', lanes: ['打野'] },
  { id: 'yixing', officialId: 197, name: '弈星', lanes: ['中路'] },
  { id: 'kuangtie', officialId: 503, name: '狂铁', lanes: ['对抗路'] },
  { id: 'milaidi', officialId: 504, name: '米莱狄', lanes: ['中路'] },
  { id: 'yuange', officialId: 125, name: '元歌', lanes: ['对抗路'] },
  { id: 'sunce', officialId: 510, name: '孙策', lanes: ['对抗路', '打野'] },
  { id: 'simayi', officialId: 137, name: '司马懿', lanes: ['打野', '中路'] },
  { id: 'dunshan', officialId: 509, name: '盾山', lanes: ['游走'] },
  { id: 'jialuo', officialId: 508, name: '伽罗', lanes: ['发育路'] },
  { id: 'shenmengxi', officialId: 312, name: '沈梦溪', lanes: ['中路'] },
  { id: 'lixin', officialId: 507, name: '李信', lanes: ['对抗路'] },
  { id: 'shangguanwaner', officialId: 513, name: '上官婉儿', lanes: ['中路'] },
  { id: 'change', officialId: 515, name: '嫦娥', lanes: ['中路', '对抗路', '打野'] },
  { id: 'zhubajie', officialId: 511, name: '猪八戒', lanes: ['对抗路', '打野'] },
  { id: 'pangu', officialId: 529, name: '盘古', lanes: ['打野', '对抗路'] },
  { id: 'yao', officialId: 505, name: '瑶', lanes: ['游走'] },
  { id: 'yunzhongjun', officialId: 506, name: '云中君', lanes: ['打野'] },
  { id: 'dongfangyao', officialId: 522, name: '曜', lanes: ['打野', '对抗路'] },
  { id: 'machao', officialId: 518, name: '马超', lanes: ['对抗路', '打野'] },
  { id: 'xishi', officialId: 523, name: '西施', lanes: ['中路'] },
  { id: 'lubandashi', officialId: 525, name: '鲁班大师', lanes: ['游走'] },
  { id: 'mengya', officialId: 524, name: '蒙犽', lanes: ['发育路'] },
  { id: 'jing', officialId: 531, name: '镜', lanes: ['打野'] },
  { id: 'mengtian', officialId: 527, name: '蒙恬', lanes: ['对抗路'] },
  { id: 'aguduo', officialId: 533, name: '阿古朵', lanes: ['打野', '发育路'] },
  { id: 'xialuote', officialId: 536, name: '夏洛特', lanes: ['对抗路'] },
  { id: 'lan', officialId: 528, name: '澜', lanes: ['打野'] },
  { id: 'sikongzhen', officialId: 537, name: '司空震', lanes: ['对抗路', '打野'] },
  { id: 'ailin', officialId: 155, name: '艾琳', lanes: ['发育路'] },
  { id: 'yunying', officialId: 538, name: '云缨', lanes: ['打野'] },
  { id: 'jinchan', officialId: 540, name: '金蝉', lanes: ['中路', '游走'] },
  { id: 'fei', officialId: 542, name: '暃', lanes: ['打野'] },
  { id: 'sangqi', officialId: 534, name: '桑启', lanes: ['游走'] },
  { id: 'geya', officialId: 548, name: '戈娅', lanes: ['发育路'] },
  { id: 'haiyue', officialId: 521, name: '海月', lanes: ['中路'] },
  { id: 'zhaohuaizhen', officialId: 544, name: '赵怀真', lanes: ['打野', '对抗路', '游走'] },
  { id: 'laixiao', officialId: 545, name: '莱西奥', lanes: ['发育路'] },
  { id: 'jixiaoman', officialId: 564, name: '姬小满', lanes: ['对抗路'] },
  { id: 'yalian', officialId: 514, name: '亚连', lanes: ['对抗路'] },
  { id: 'duoliya', officialId: 159, name: '朵莉亚', lanes: ['游走'] },
  { id: 'hainuo', officialId: 563, name: '海诺', lanes: ['中路', '对抗路'] },
  { id: 'aoyin', officialId: 519, name: '敖隐', lanes: ['发育路'] },
  { id: 'dasiming', officialId: 517, name: '大司命', lanes: ['打野', '对抗路'] },
  { id: 'yuanliuzhizi_magic', officialId: 582, name: '元流之子(法师)', lanes: ['中路'] },
  { id: 'yuanliuzhizi_tank', officialId: 581, name: '元流之子(坦克)', lanes: ['对抗路', '打野'] },
  { id: 'shaosiyuan', officialId: 577, name: '少司缘', lanes: ['游走'] },
  { id: 'ying', officialId: 558, name: '影', lanes: ['对抗路', '打野'] },
  { id: 'cang', officialId: 177, name: '苍', lanes: ['发育路', '打野'] },
  { id: 'kongkonger', officialId: 550, name: '空空儿', lanes: ['游走'] },
  { id: 'yuanliuzhizi_archer', officialId: 584, name: '元流之子(射手)', lanes: ['发育路'] },
  { id: 'sunquan', officialId: 151, name: '孙权', lanes: ['发育路'] },
  { id: 'chicha', officialId: 172, name: '蚩奼', lanes: ['对抗路', '打野'] },
  { id: 'yuanliuzhizi_support', officialId: 585, name: '元流之子(辅助)', lanes: ['游走'] },
  { id: 'dayu', officialId: 188, name: '大禹', lanes: ['游走'] },
  { id: 'yuanliuzhizi_assassin', officialId: 583, name: '元流之子(刺客)', lanes: ['打野'] },
  { id: 'luyana', officialId: 547, name: '卢雅那', lanes: ['游走'] },
  { id: 'wangwei', officialId: 138, name: '王维', lanes: ['打野'] },
]

/** 按名称反查英雄（名称唯一由 test/draw.test.ts 保证），用于从历史记录里的英雄名快照取回官方形象 */
export function findHeroByName(name: string): Hero | undefined {
  return heroes.find(hero => hero.name === name)
}
